import Provider from '@/context/client-provider';
import {UtilsProvider} from '@/context/utils-provider';

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/route';

import ClientOnly from './ClientsOnly';

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Marvel App',
  description: 'Generated by create next app',
}




export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  const session = await getServerSession(authOptions);


  return (
    <html lang="en">
      <Provider session={session} >
      <ClientOnly/>
        <UtilsProvider>
        <body className={inter.className}>
          <main className='className="flex min-h-screen flex-col zitems-center justify-between p-24"' >
            {children}
          </main>
        </body>
        </UtilsProvider>
      </Provider>
    </html>
  )
}
